import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { ContactAgentSection } from '../components/Home/ContactAgentSection'
import { DevelopmentSection } from '../components/Home/DevelopmentSection'
import { Hero } from '../components/Home/Hero'
import { ListingSection } from '../components/Home/ListingSection'
import { Layout } from '../components/Layout'
import { Footer } from '../components/Layout/Footer'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout isTransparent>
        <Hero />

        <ListingSection />

        <DevelopmentSection />

        <ContactAgentSection />

        <Footer />
      </Layout>
    </>
  )
}

export default Home
